# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-14 00:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listed_agent_name', models.CharField(max_length=20)),
                ('listed_email', models.EmailField(max_length=254)),
                ('listed_phone_number', models.CharField(max_length=20)),
                ('leads_from_email', models.EmailField(max_length=254)),
                ('leads_to_email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Contact Info',
            },
        ),
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(max_length=254, null=True)),
                ('to_email', models.EmailField(max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Email Settings',
            },
        ),
        migrations.CreateModel(
            name='ExtraImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additionalimage', models.ImageField(upload_to=b'images')),
                ('description', models.TextField(blank=True, default=b'', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default=b'')),
                ('city', models.TextField(default=b'')),
                ('state', models.TextField(default=b'')),
                ('street', models.TextField(default=b'')),
                ('price', models.IntegerField(default=b'')),
                ('sold', models.BooleanField(default=False)),
                ('numofbeds', models.CharField(blank=True, default=b'', max_length=10000)),
                ('numofbaths', models.CharField(blank=True, default=b'', max_length=10000)),
                ('is_premium', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'images')),
                ('published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MLSNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=50, null=True)),
                ('home_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Home')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=12, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='favorites',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Home'),
        ),
        migrations.AddField(
            model_name='favorites',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='extraimage',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Home'),
        ),
        migrations.AlterUniqueTogether(
            name='favorites',
            unique_together=set([('user', 'list')]),
        ),
    ]
