# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-24 00:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_home_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='description',
            new_name='title',
        ),
    ]
