# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-24 00:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20161124_0043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extraimages',
            old_name='image',
            new_name='adimage',
        ),
    ]
