# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-01 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20161124_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraimages',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
