# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-16 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170316_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userid',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
    ]
