# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-01 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_extraimages_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraimages',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
