# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-17 00:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170316_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='userid',
        ),
    ]
