# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-17 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_profile_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='userid',
            field=models.CharField(max_length=100000, null=True),
        ),
    ]
