# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-02 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20161201_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='list',
            field=models.TextField(default=''),
        ),
    ]
