# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-24 00:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170323_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='leads_from_email',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='leads_to_email',
        ),
    ]
