# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-02 02:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20161202_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Home'),
        ),
    ]
