# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-03 00:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_auto_20161202_0203'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorites',
            unique_together=set([('user', 'list')]),
        ),
    ]
