# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-03 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_usermodel_temp_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='company_info',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
