# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-03 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20161203_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='price',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
