# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-03 01:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_home_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extraimages',
            old_name='adimage',
            new_name='additionalimage',
        ),
    ]
