# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-03 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_contactinfo_company_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='company_info',
            field=models.TextField(blank=True, max_length=10000),
        ),
    ]
