# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-04 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20170403_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b'images'),
        ),
    ]
