# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-23 23:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_contactinfo_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailsettings',
            options={'verbose_name_plural': 'Lead Email Settings'},
        ),
    ]
