# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20161213_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='reference_number',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
