# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_home_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=b'thumbnails'),
        ),
    ]
