# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 00:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_home_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLSNumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='home',
            name='reference_number',
        ),
        migrations.RemoveField(
            model_name='home',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='home',
            name='MLS_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.MLSNumbers'),
        ),
    ]
