# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 00:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20161228_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlsnumbers',
            name='home_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Home'),
        ),
    ]
