# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 00:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_mlsnumbers_home_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MLSNumbers',
            new_name='MLSNumber',
        ),
    ]
