# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 00:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20161228_0052'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExtraImages',
            new_name='ExtraImage',
        ),
    ]
