# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 01:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20161228_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='MLS_number',
        ),
        migrations.RemoveField(
            model_name='home',
            name='deleted',
        ),
    ]
