# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-21 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20170114_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listed_agent_name', models.CharField(max_length=20)),
                ('listed_email', models.EmailField(max_length=254)),
                ('listed_phone_number', models.IntegerField()),
                ('leads_from_email', models.EmailField(max_length=254)),
                ('leads_to_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
