# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_contactinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(max_length=254)),
                ('to_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='listed_phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
