# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-07 01:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20170124_0101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name_plural': 'Contact Info'},
        ),
        migrations.AlterModelOptions(
            name='emailsettings',
            options={'verbose_name_plural': 'Email Settings'},
        ),
    ]
